import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import Footer from "@/components/footer/Footer";

const geist = Geist({
  subsets: ["latin"],
  display: "swap",
});
const geistMono = Geist_Mono({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App ", // title of the app
  description: "Generated by create next app", // description of the app
  keywords: "nextjs, react, app", // keywords for SEO
  authors: [{ name: "Your Name", url: "https://yourwebsite.com" }], // author information
  creator: "Your Name", // creator of the app
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geist.className} ${geistMono.className}`}>
        <div className="container">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
